<?php

/*
|--------------------------------------------------------------------------
| SEO Landing Pages
|--------------------------------------------------------------------------
| Each entry drives a dedicated SEO landing page (/invoicing-software,
| /online-invoice-software, etc.). The shared `common` block is merged
| into every page unless a page overrides a key.
*/

return [

    'common' => [

        'screenshots' => [
            [
                'image' => 'hero-invoice.jpg',
                'alt' => 'Inveqi invoice management dashboard showing invoices, totals and payment status',
                'title' => 'Build perfect invoices in minutes',
                'desc' => 'Use the drag-and-drop invoice builder to add line items, apply taxes and discounts, and drop in your logo. Everything updates in real time as you type.',
                'points' => ['Drag-and-drop line items', 'Apply taxes & discounts', 'Upload your logo & branding', 'Live PDF and email preview'],
            ],
            [
                'image' => 'hero-invoice.jpg',
                'alt' => 'Inveqi recurring billing screen showing automated invoice schedules',
                'title' => 'Automate your billing cycle',
                'desc' => 'Set up recurring invoices for subscriptions and retainers. Inveqi creates and sends each invoice on schedule, so nothing slips through the cracks.',
                'points' => ['Weekly, monthly & yearly schedules', 'Pause, resume or clone series', 'Automatic payment reminders', 'Track every schedule at a glance'],
            ],
            [
                'image' => 'hero-invoice.jpg',
                'alt' => 'Inveqi estimates and quotes approval screen',
                'title' => 'From quote to invoice in one step',
                'desc' => 'Send a polished estimate, let your client approve it online, and watch it turn into an invoice automatically. No copy-paste, no double entry.',
                'points' => ['One-click client approval', 'Auto-convert estimates to invoices', 'Expiry dates & version history', 'Professional branded templates'],
            ],
        ],

    ],

    'pages' => [

        'invoicing-software' => [
            'slug' => 'invoicing-software',
            'kicker' => 'Invoicing Software',
            'h1' => 'Invoicing software',
            'h1_highlight' => 'for modern businesses',
            'title' => 'Invoicing Software | Create, Send & Track Invoices Online | Inveqi',
            'meta_description' => 'Invoicing software to create professional invoices, send them by email, track payments and automate follow-ups. Start your free 14-day trial.',
            'meta_keywords' => 'invoicing software, invoice management software, create invoice, send invoice online, track invoices, invoice tracking, invoice follow-up, get paid faster',
            'subtitle' => 'Create beautiful invoices in seconds, send them by email, and track payments with automatic reminders â€” all in one secure workspace built for small businesses.',
            'cta_text' => 'Start your free trial',
            'screenshots_intro' => 'Everything from the invoice builder to payment tracking, in one workspace.',
            'benefits_title' => 'Why businesses choose Inveqi invoicing software',
            'benefits_intro' => 'Stop juggling spreadsheets and email. Inveqi keeps every invoice organized and every payment on track.',
            'benefits' => [
                ['icon' => 'fa-bolt', 'title' => 'Create invoices faster', 'desc' => 'Drag-and-drop builder turns a blank invoice into a ready-to-send document in under a minute.'],
                ['icon' => 'fa-bell', 'title' => 'Get paid on time', 'desc' => 'Automatic payment reminders and overdue alerts nudge customers so invoices get paid faster.'],
                ['icon' => 'fa-chart-line', 'title' => 'Know where you stand', 'desc' => 'Real-time dashboards show revenue, outstanding balances and payment trends at a glance.'],
                ['icon' => 'fa-shield-halved', 'title' => 'Look professional', 'desc' => '10+ branded templates and PDF export give every invoice a polished, consistent look.'],
                ['icon' => 'fa-cloud', 'title' => 'Access from anywhere', 'desc' => 'Secure cloud workspace works in any browser, so you can invoice from the office or on the go.'],
                ['icon' => 'fa-credit-card', 'title' => 'Accept payments online', 'desc' => 'Add Stripe so customers can pay invoices instantly by card.'],
            ],
            'features_title' => 'Everything you need in invoicing software',
            'features_intro' => 'A complete toolkit to create, send and get paid.',
            'features' => [
                ['icon' => 'fa-file-invoice', 'title' => 'Invoice builder', 'desc' => 'Add line items, taxes, discounts, photos and custom fields with an intuitive drag-and-drop editor.'],
                ['icon' => 'fa-envelope', 'title' => 'Email invoicing', 'desc' => 'Send invoices directly from your workspace with tracked delivery and view status.'],
                ['icon' => 'fa-credit-card', 'title' => 'Card payments', 'desc' => 'Collect payments with secure Stripe integration and reconcile automatically.'],
                ['icon' => 'fa-bell', 'title' => 'Payment reminders', 'desc' => 'Automated, polite follow-up emails go out on schedules you control.'],
                ['icon' => 'fa-chart-bar', 'title' => 'Reports & analytics', 'desc' => 'Understand revenue, outstanding balances and customer payment behavior.'],
                ['icon' => 'fa-file-pdf', 'title' => 'PDF export', 'desc' => 'Download beautiful, print-ready PDF invoices for records or offline sending.'],
                ['icon' => 'fa-users', 'title' => 'Team access', 'desc' => 'Invite staff with role-based permissions for admins, managers and accountants.'],
                ['icon' => 'fa-cubes', 'title' => 'Product catalog', 'desc' => 'Maintain a reusable product and service catalog with prices and tax rules.'],
                ['icon' => 'fa-palette', 'title' => 'Invoice templates', 'desc' => 'Choose from 10+ designs or customize with your own brand colors and CSS.'],
            ],
            'use_cases_title' => 'Who invoicing software helps most',
            'use_cases_intro' => 'Freelancers, agencies and small businesses use Inveqi to get paid reliably.',
            'use_cases' => [
                ['icon' => 'fa-user-tie', 'title' => 'Freelancers', 'desc' => 'Send one-off invoices for projects and get paid by card without chasing checks.'],
                ['icon' => 'fa-building', 'title' => 'Agencies', 'desc' => 'Bill retainers and projects, track time-based invoices and manage many clients.'],
                ['icon' => 'fa-store', 'title' => 'Small businesses', 'desc' => 'Keep invoicing, payments and reports in one simple workspace your team can use.'],
                ['icon' => 'fa-handshake', 'title' => 'Consultants & services', 'desc' => 'Turn quotes into invoices, schedule recurring billing and collect online payments.'],
            ],
            'internal_links' => [
                ['title' => 'Online Invoice Software', 'url' => '/online-invoice-software', 'desc' => 'Create and send invoices entirely from your browser.'],
                ['title' => 'Invoice Generator', 'url' => '/invoice-generator', 'desc' => 'Generate a professional invoice for free in seconds.'],
                ['title' => 'Invoice Management Software', 'url' => '/invoice-management-software', 'desc' => 'Track, organize and manage every invoice in one place.'],
                ['title' => 'Recurring Invoicing', 'url' => '/recurring-invoicing', 'desc' => 'Automate repeat invoices for subscriptions and retainers.'],
                ['title' => 'Stripe Invoicing', 'url' => '/stripe-invoicing', 'desc' => 'Accept card payments directly on every invoice.'],
                ['title' => 'Billing Software', 'url' => '/billing-software', 'desc' => 'Streamline your whole billing workflow.'],
            ],
            'faqs_title' => 'Invoicing software FAQ',
            'faqs' => [
                ['q' => 'What is invoicing software?', 'a' => 'Invoicing software helps you create, send and track invoices, collect payments and report on revenue â€” replacing spreadsheets and manual follow-ups.'],
                ['q' => 'Can I start for free?', 'a' => 'Yes. Every plan includes a 14-day free trial with no credit card required, and there is a free Starter plan for freelancers.'],
                ['q' => 'How do I get paid with invoicing software?', 'a' => 'With Inveqi you can add Stripe so customers click a link in their invoice email and pay by credit card instantly.'],
                ['q' => 'Is my data secure?', 'a' => 'Yes. All data is encrypted at rest and in transit, and each organization is isolated in a secure multi-tenant architecture.'],
                ['q' => 'Can I send automatic payment reminders?', 'a' => 'Yes. Turn on automated reminders to send polite follow-up emails at intervals you choose until overdue invoices are paid.'],
            ],
            'schema' => '{
                "@context": "https://schema.org",
                "@type": "SoftwareApplication",
                "name": "Inveqi Invoicing Software",
                "applicationCategory": "BusinessApplication",
                "operatingSystem": "Web",
                "url": "__CANONICAL__",
                "description": "Invoicing software to create, send and track professional invoices and get paid faster with Stripe.",
                "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
                "aggregateRating": { "@type": "AggregateRating", "ratingValue": "4.8", "ratingCount": "128" }
            }',
        ],

        'online-invoice-software' => [
            'slug' => 'online-invoice-software',
            'kicker' => 'Online Invoice Software',
            'h1' => 'Online invoice software',
            'h1_highlight' => 'â€” no downloads, no clutter',
            'title' => 'Online Invoice Software | Create & Send Invoices in Your Browser | Inveqi',
            'meta_description' => 'Online invoice software that works entirely in your browser. Create polished invoices, email them, and collect Stripe payments from anywhere. Start free today.',
            'meta_keywords' => 'online invoice software, web invoice software, create invoice online, online invoicing, browser invoice, web invoicing, online billing',
            'subtitle' => 'The web-based invoicing tool that lets you create, send and track invoices from any device â€” signing in, creating and emailing in under a minute.',
            'cta_text' => 'Create your first invoice',
            'screenshots_intro' => 'A cloud workspace that works wherever you do.',
            'benefits_title' => 'The power of online invoicing',
            'benefits_intro' => 'Because it runs in your browser, Inveqi works on every device without a single download.',
            'benefits' => [
                ['icon' => 'fa-globe', 'title' => 'Work from anywhere', 'desc' => 'Your invoices live in the cloud, so you can create and send them from any computer or tablet.'],
                ['icon' => 'fa-rocket', 'title' => 'Up and running in minutes', 'desc' => 'Sign up, add your first customer, and email a professional invoice in under five minutes.'],
                ['icon' => 'fa-sync', 'title' => 'Always up to date', 'desc' => 'No installations or updates to manage â€” you always have the latest features.'],
                ['icon' => 'fa-lock', 'title' => 'Secure by design', 'desc' => 'Bank-grade encryption and secure sign-in keep your billing data protected.'],
                ['icon' => 'fa-bolt', 'title' => 'Faster billing', 'desc' => 'Send a polished invoice in under 30 seconds from any device.'],
                ['icon' => 'fa-mobile-screen', 'title' => 'Mobile friendly', 'desc' => 'Create and review invoices on the go with a responsive browser experience.'],
            ],
            'features_title' => 'Features that make online invoicing effortless',
            'features_intro' => 'Everything you expect from modern invoicing tools â€” without the setup.',
            'features' => [
                ['icon' => 'fa-file-invoice', 'title' => 'Browser invoice builder', 'desc' => 'Build professional invoices in your browser with a drag-and-drop editor.'],
                ['icon' => 'fa-envelope', 'title' => 'Email delivery', 'desc' => 'Send invoices from the workspace and track when customers open them.'],
                ['icon' => 'fa-credit-card', 'title' => 'Stripe payments', 'desc' => 'Let customers pay online by card with a secure payment link.'],
                ['icon' => 'fa-repeat', 'title' => 'Recurring billing', 'desc' => 'Automate repeat invoices from the web with zero manual effort.'],
                ['icon' => 'fa-cloud', 'title' => 'Cloud sync', 'desc' => 'Your data stays synced across devices automatically.'],
                ['icon' => 'fa-shield-halved', 'title' => 'Bank-grade security', 'desc' => 'Encrypted, isolated workspaces keep your data safe.'],
                ['icon' => 'fa-palette', 'title' => '10+ templates', 'desc' => 'Professionally designed templates you can brand to match your business.'],
                ['icon' => 'fa-chart-line', 'title' => 'Live reports', 'desc' => 'Dashboard insights on revenue and outstanding balances, updated live.'],
                ['icon' => 'fa-users', 'title' => 'Team collaboration', 'desc' => 'Invite your team to work together inside the same online workspace.'],
            ],
            'use_cases_title' => 'Who uses online invoicing',
            'use_cases_intro' => 'Anyone who sends invoices from more than one device.',
            'use_cases' => [
                ['icon' => 'fa-laptop', 'title' => 'Remote teams', 'desc' => 'Team members invoice from anywhere while staying in sync.'],
                ['icon' => 'fa-user-tie', 'title' => 'Freelancers', 'desc' => 'Send invoices and collect payments without desktop software.'],
                ['icon' => 'fa-plane', 'title' => 'Travelers', 'desc' => 'Create and send invoices on the go from any browser.'],
                ['icon' => 'fa-store', 'title' => 'Online businesses', 'desc' => 'Automate billing for digital products and services.'],
            ],
            'internal_links' => [
                ['title' => 'Invoicing Software', 'url' => '/invoicing-software', 'desc' => 'The complete invoicing platform for modern teams.'],
                ['title' => 'Invoice Generator', 'url' => '/invoice-generator', 'desc' => 'Generate professional invoices for free.'],
                ['title' => 'Small Business Invoicing', 'url' => '/small-business-invoicing', 'desc' => 'Invoicing built for small businesses.'],
                ['title' => 'Billing Software', 'url' => '/billing-software', 'desc' => 'Streamline your entire billing workflow.'],
            ],
            'faqs_title' => 'Online invoice software FAQ',
            'faqs' => [
                ['q' => 'Do I need to install anything?', 'a' => 'No. Inveqi runs entirely in your web browser, so there is no software to download or update.'],
                ['q' => 'Can I use it on my phone or tablet?', 'a' => 'Yes. The web app is fully responsive, so you can create and review invoices from any device.'],
                ['q' => 'How do customers pay online?', 'a' => 'With Stripe enabled, customers click a link in the invoice email and pay by credit card on a secure page.'],
                ['q' => 'Is my online data backed up?', 'a' => 'Yes. Your invoices live in a secure cloud database that is encrypted and protected against loss.'],
            ],
            'schema' => '{
                "@context": "https://schema.org",
                "@type": "SoftwareApplication",
                "name": "Inveqi Online Invoice Software",
                "applicationCategory": "BusinessApplication",
                "operatingSystem": "Web",
                "url": "__CANONICAL__",
                "description": "Online invoice software to create and send professional invoices from any browser.",
                "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
                "aggregateRating": { "@type": "AggregateRating", "ratingValue": "4.8", "ratingCount": "128" }
            }',
        ],

        'invoice-management-software' => [
            'slug' => 'invoice-management-software',
            'kicker' => 'Invoice Management Software',
            'h1' => 'Invoice management software',
            'h1_highlight' => 'for total control',
            'title' => 'Invoice Management Software | Organize Track & Report | Inveqi',
            'meta_description' => 'Invoice management software to organize every invoice, track payment status and report on revenue. Centralize your billing with Inveqi. Start free for 14 days.',
            'meta_keywords' => 'invoice management software, invoice tracking, manage invoices, invoice organization, accounts receivable software, invoice dashboard',
            'subtitle' => 'Stop losing track of unpaid invoices. Inveqi centralizes creation, sending, payment tracking and reporting so you always know exactly where each invoice stands.',
            'cta_text' => 'Get organized',
            'screenshots_intro' => 'A command center for every invoice in your business.',
            'benefits_title' => 'Why centralized invoice management wins',
            'benefits_intro' => 'When everything lives in one system, nothing gets missed.',
            'benefits' => [
                ['icon' => 'fa-folder-tree', 'title' => 'One source of truth', 'desc' => 'Every invoice, customer and payment lives in a single organized system.'],
                ['icon' => 'fa-bell', 'title' => 'Never miss a payment', 'desc' => 'Spot overdue invoices instantly and automate follow-up reminders.'],
                ['icon' => 'fa-chart-pie', 'title' => 'See your revenue clearly', 'desc' => 'Dashboards show what is billed, paid and outstanding at a glance.'],
                ['icon' => 'fa-search', 'title' => 'Find any invoice instantly', 'desc' => 'Powerful search and filters make locating a specific invoice effortless.'],
                ['icon' => 'fa-user-check', 'title' => 'Know your customers', 'desc' => 'Understand who pays on time and who needs a nudge, per customer.'],
                ['icon' => 'fa-file-export', 'title' => 'Export when you need', 'desc' => 'Pull PDFs, CSVs and reports for records, tax time or accounting.'],
            ],
            'features_title' => 'Complete invoice management features',
            'features_intro' => 'A full toolkit for keeping your billing under control.',
            'features' => [
                ['icon' => 'fa-table', 'title' => 'Invoice dashboard', 'desc' => 'See all invoices, statuses and balances in one organized view.'],
                ['icon' => 'fa-filter', 'title' => 'Search & filters', 'desc' => 'Find invoices by number, customer, status or date range instantly.'],
                ['icon' => 'fa-circle-half-stroke', 'title' => 'Status tracking', 'desc' => 'Track draft, sent, paid and overdue states with visual labels.'],
                ['icon' => 'fa-bell', 'title' => 'Reminders', 'desc' => 'Automated follow-ups keep overdue invoices front of mind.'],
                ['icon' => 'fa-chart-pie', 'title' => 'Analytics', 'desc' => 'Reports on revenue, aging and customer payment behavior.'],
                ['icon' => 'fa-file-export', 'title' => 'Export & reports', 'desc' => 'Generate CSV and PDF exports for accounting and tax.'],
                ['icon' => 'fa-repeat', 'title' => 'Recurring management', 'desc' => 'Manage recurring series alongside one-off invoices.'],
                ['icon' => 'fa-users', 'title' => 'Team permissions', 'desc' => 'Control who can view, create or edit invoices.'],
                ['icon' => 'fa-cloud', 'title' => 'Cloud access', 'desc' => 'Manage everything securely from any device.'],
            ],
            'use_cases_title' => 'Who needs invoice management software',
            'use_cases_intro' => 'Anyone dealing with high invoice volume or overdue tracking.',
            'use_cases' => [
                ['icon' => 'fa-file-invoice-dollar', 'title' => 'High-volume billers', 'desc' => 'Handle hundreds of invoices without losing track of any.'],
                ['icon' => 'fa-scale-balanced', 'title' => 'Accountants & bookkeepers', 'desc' => 'Manage client billing, reconcile payments and export clean reports.'],
                ['icon' => 'fa-building', 'title' => 'Growing agencies', 'desc' => 'Track multiple projects, clients and payment statuses in one place.'],
                ['icon' => 'fa-store', 'title' => 'Subscription businesses', 'desc' => 'Manage recurring billing and payment health across many customers.'],
            ],
            'internal_links' => [
                ['title' => 'Invoice Automation', 'url' => '/invoice-automation', 'desc' => 'Automate reminders, billing and follow-ups.'],
                ['title' => 'Invoicing Software', 'url' => '/invoicing-software', 'desc' => 'Create, send and track invoices online.'],
                ['title' => 'Recurring Invoicing', 'url' => '/recurring-invoicing', 'desc' => 'Automate repeat billing with ease.'],
                ['title' => 'Billing Software', 'url' => '/billing-software', 'desc' => 'Streamline your complete billing process.'],
            ],
            'faqs_title' => 'Invoice management FAQ',
            'faqs' => [
                ['q' => 'What does invoice management software do?', 'a' => 'It centralizes creating, sending, tracking and reporting on invoices, so you know which are paid, unpaid or overdue at all times.'],
                ['q' => 'Can I track overdue invoices?', 'a' => 'Yes. Inveqi highlights overdue invoices and can send automatic payment reminders.'],
                ['q' => 'Can I export reports for my accountant?', 'a' => 'Yes. Export clean CSV and PDF reports for accounting, tax and reconciliation.'],
                ['q' => 'Is it suitable for high invoice volume?', 'a' => 'Yes. Business plans support unlimited invoices with fast search and filtering.'],
            ],
            'schema' => '{
                "@context": "https://schema.org",
                "@type": "SoftwareApplication",
                "name": "Inveqi Invoice Management Software",
                "applicationCategory": "BusinessApplication",
                "operatingSystem": "Web",
                "url": "__CANONICAL__",
                "description": "Invoice management software to organize, track and report on every invoice.",
                "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
                "aggregateRating": { "@type": "AggregateRating", "ratingValue": "4.8", "ratingCount": "128" }
            }',
        ],

        'invoice-generator' => [
            'slug' => 'invoice-generator',
            'kicker' => 'Invoice Generator',
            'h1' => 'Free invoice generator',
            'h1_highlight' => 'create a professional invoice in seconds',
            'title' => 'Free Invoice Generator | Make Professional Invoices Online | Inveqi',
            'meta_description' => 'Generate a professional, customizable invoice online in seconds with the free Inveqi invoice generator. Add line items, your logo, and email it instantly. Try free.',
            'meta_keywords' => 'invoice generator, free invoice generator, create invoice, invoice maker, make an invoice, invoice builder online, invoice template generator',
            'subtitle' => 'Fill in the details, add your line items, and download or email a polished, fully branded invoice â€” free, no credit card required.',
            'cta_text' => 'Generate your first invoice',
            'screenshots_intro' => 'Turn a blank page into a ready-to-send invoice in seconds.',
            'benefits_title' => 'Why start with an invoice generator',
            'benefits_intro' => 'Skip the template anxiety and create something professional on your first try.',
            'benefits' => [
                ['icon' => 'fa-timer', 'title' => 'Done in under a minute', 'desc' => 'A guided generator turns your details into a polished invoice fast.'],
                ['icon' => 'fa-brush', 'title' => 'Looks professional', 'desc' => 'Clean, modern templates make you look established from day one.'],
                ['icon' => 'fa-wand-magic-sparkles', 'title' => 'No design skills needed', 'desc' => 'Add line items, totals and your logo without touching a designer.'],
                ['icon' => 'fa-file-arrow-down', 'title' => 'Download or send', 'desc' => 'Get a PDF or email it straight to your customer.'],
                ['icon' => 'fa-gem', 'title' => 'Fully customizable', 'desc' => 'Choose colors, layout and fields to match your brand.'],
                ['icon' => 'fa-credit-card', 'title' => 'Collect payments', 'desc' => 'Add a payment link so customers can pay generated invoices online.'],
            ],
            'features_title' => 'Powerful generator features',
            'features_intro' => 'All the tools to create the perfect invoice.',
            'features' => [
                ['icon' => 'fa-list-ul', 'title' => 'Line item editor', 'desc' => 'Add products, services, quantities and rates in a simple table.'],
                ['icon' => 'fa-percent', 'title' => 'Taxes & discounts', 'desc' => 'Apply tax rates and discounts that recalculate automatically.'],
                ['icon' => 'fa-image', 'title' => 'Logo upload', 'desc' => 'Upload your logo to brand every generated invoice.'],
                ['icon' => 'fa-palette', 'title' => 'Template picker', 'desc' => 'Choose from 10+ designs to set the right tone.'],
                ['icon' => 'fa-file-pdf', 'title' => 'Instant PDF', 'desc' => 'Preview and download a print-ready PDF in one click.'],
                ['icon' => 'fa-envelope', 'title' => 'Email as PDF', 'desc' => 'Send the invoice directly from the generator to your customer.'],
                ['icon' => 'fa-address-card', 'title' => 'Custom fields', 'desc' => 'Add PO numbers, project codes or notes to any invoice.'],
                ['icon' => 'fa-language', 'title' => 'Multi-currency', 'desc' => 'Generate invoices in the currency that suits each client.'],
                ['icon' => 'fa-user-plus', 'title' => 'Save customers', 'desc' => 'Store customer details to speed up future invoices.'],
            ],
            'use_cases_title' => 'Who uses the invoice generator',
            'use_cases_intro' => 'From one-off jobs to regular billing.',
            'use_cases' => [
                ['icon' => 'fa-hammer', 'title' => 'Freelancers & trades', 'desc' => 'Generate an invoice on the spot after a job is done.'],
                ['icon' => 'fa-camera', 'title' => 'Service providers', 'desc' => 'Quickly bill for a single service or project.'],
                ['icon' => 'fa-store', 'title' => 'Small shops', 'desc' => 'Create a professional receipt-style invoice for any sale.'],
                ['icon' => 'fa-graduation-cap', 'title' => 'Tutors & coaches', 'desc' => 'Invoice for lessons and sessions without bulky software.'],
            ],
            'internal_links' => [
                ['title' => 'Online Invoice Software', 'url' => '/online-invoice-software', 'desc' => 'The full online invoicing workflow.'],
                ['title' => 'Invoicing Software', 'url' => '/invoicing-software', 'desc' => 'Create, send and track invoices online.'],
                ['title' => 'Small Business Invoicing', 'url' => '/small-business-invoicing', 'desc' => 'Invoicing built for small business.'],
                ['title' => 'Estimate Invoice Software', 'url' => '/estimate-invoice-software', 'desc' => 'Turn estimates into invoices automatically.'],
            ],
            'faqs_title' => 'Invoice generator FAQ',
            'faqs' => [
                ['q' => 'Is the invoice generator really free?', 'a' => 'Yes. You can generate and download invoices for free, and paid plans add unlimited volume and extra features.'],
                ['q' => 'Can I add my logo and branding?', 'a' => 'Absolutely. Upload your logo and pick colors and templates to match your business.'],
                ['q' => 'How do I send the invoice to my customer?', 'a' => 'Email it directly as a PDF from Inveqi, or download and send it however you like.'],
                ['q' => 'Can customers pay my generated invoice online?', 'a' => 'Yes, with Stripe enabled customers can pay by clicking a secure link in the invoice.'],
            ],
            'schema' => '{
                "@context": "https://schema.org",
                "@type": "SoftwareApplication",
                "name": "Inveqi Invoice Generator",
                "applicationCategory": "BusinessApplication",
                "operatingSystem": "Web",
                "url": "__CANONICAL__",
                "description": "Free online invoice generator to create and send professional invoices.",
                "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
                "aggregateRating": { "@type": "AggregateRating", "ratingValue": "4.8", "ratingCount": "128" }
            }',
        ],

        'billing-software' => [
            'slug' => 'billing-software',
            'kicker' => 'Billing Software',
            'h1' => 'Billing software',
            'h1_highlight' => 'that pays for itself',
            'title' => 'Billing Software | Automate Invoicing & Payments | Inveqi',
            'meta_description' => 'Billing software to invoice clients, collect payments and automate recurring billing. Save hours every month with Inveqi. Start your free 14-day trial.',
            'meta_keywords' => 'billing software, billing system, automated billing, billing and invoicing, recurring billing software, payment collection software',
            'subtitle' => 'Replace manual billing chaos with one automated system that invoices clients, collects payments and keeps your cash flow healthy.',
            'cta_text' => 'Automate your billing',
            'screenshots_intro' => 'See how billing flows from invoice to payment automatically.',
            'benefits_title' => 'The benefits of automated billing',
            'benefits_intro' => 'Automation removes the busywork and the mistakes.',
            'benefits' => [
                ['icon' => 'fa-clock', 'title' => 'Save hours every month', 'desc' => 'Automate repeat invoices, reminders and reconciliation.'],
                ['icon' => 'fa-coins', 'title' => 'Improve cash flow', 'desc' => 'Get paid faster with online payments and automatic follow-ups.'],
                ['icon' => 'fa-robot', 'title' => 'Fewer billing errors', 'desc' => 'Consistent templates and auto-calculated totals reduce mistakes.'],
                ['icon' => 'fa-repeat', 'title' => 'Recurring income', 'desc' => 'Set subscriptions and retainers to bill themselves each cycle.'],
                ['icon' => 'fa-chart-line', 'title' => 'Clear financial view', 'desc' => 'See revenue, outstanding balances and trends in real time.'],
                ['icon' => 'fa-user-group', 'title' => 'Team-ready', 'desc' => 'Give staff the right access so billing stays organized.'],
            ],
            'features_title' => 'Everything in one billing system',
            'features_intro' => 'Invoicing, payments and automation combined.',
            'features' => [
                ['icon' => 'fa-file-invoice', 'title' => 'Professional invoices', 'desc' => 'Create on-brand, accurate invoices every time.'],
                ['icon' => 'fa-repeat', 'title' => 'Recurring billing', 'desc' => 'Automatically bill customers on any schedule.'],
                ['icon' => 'fa-credit-card', 'title' => 'Online payments', 'desc' => 'Collect card payments through secure Stripe integration.'],
                ['icon' => 'fa-bell', 'title' => 'Automatic reminders', 'desc' => 'Nudge overdue customers without lifting a finger.'],
                ['icon' => 'fa-chart-pie', 'title' => 'Revenue reports', 'desc' => 'Track cash flow and outstanding balances at a glance.'],
                ['icon' => 'fa-file-arrow-down', 'title' => 'PDF & CSV export', 'desc' => 'Export clean records for accounting and tax.'],
                ['icon' => 'fa-key', 'title' => 'User permissions', 'desc' => 'Control exactly who can create and edit billing.'],
                ['icon' => 'fa-cloud', 'title' => 'Secure cloud', 'desc' => 'Encrypted, always-available billing workspace.'],
                ['icon' => 'fa-plug', 'title' => 'Webhooks & API', 'desc' => 'Connect billing to your other tools programmatically.'],
            ],
            'use_cases_title' => 'Billing software for every need',
            'use_cases_intro' => 'Flexible enough for simple and complex billing alike.',
            'use_cases' => [
                ['icon' => 'fa-satellite-dish', 'title' => 'Subscription businesses', 'desc' => 'Bill customers every month without touching it.'],
                ['icon' => 'fa-truck', 'title' => 'Product businesses', 'desc' => 'Invoice orders and collect payment online.'],
                ['icon' => 'fa-briefcase', 'title' => 'Service agencies', 'desc' => 'Bill retainers, projects and recurring engagements.'],
                ['icon' => 'fa-dollar-sign', 'title' => 'Freelancers', 'desc' => 'Keep invoicing simple and get paid on time.'],
            ],
            'internal_links' => [
                ['title' => 'Recurring Invoicing', 'url' => '/recurring-invoicing', 'desc' => 'Automate recurring billing end to end.'],
                ['title' => 'Stripe Invoicing', 'url' => '/stripe-invoicing', 'desc' => 'Accept payments directly on invoices.'],
                ['title' => 'Invoice Automation', 'url' => '/invoice-automation', 'desc' => 'Automate reminders and billing workflows.'],
                ['title' => 'Billing Software', 'url' => '/billing-software', 'desc' => 'Explore the full billing platform.'],
            ],
            'faqs_title' => 'Billing software FAQ',
            'faqs' => [
                ['q' => 'What is billing software?', 'a' => 'Billing software streamlines creating invoices, collecting payments and managing recurring charges automatically.'],
                ['q' => 'Can it handle recurring billing?', 'a' => 'Yes. Inveqi can automatically generate and send invoices on weekly, monthly or yearly schedules.'],
                ['q' => 'How do I collect payments?', 'a' => 'Enable Stripe so customers can pay invoices online by credit card through a secure link.'],
                ['q' => 'Can I export data for my accountant?', 'a' => 'Yes. Export clean CSV and PDF reports for accounting and tax filing.'],
            ],
            'schema' => '{
                "@context": "https://schema.org",
                "@type": "SoftwareApplication",
                "name": "Inveqi Billing Software",
                "applicationCategory": "BusinessApplication",
                "operatingSystem": "Web",
                "url": "__CANONICAL__",
                "description": "Billing software to automate invoicing, payments and recurring billing.",
                "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
                "aggregateRating": { "@type": "AggregateRating", "ratingValue": "4.8", "ratingCount": "128" }
            }',
        ],

        'recurring-invoicing' => [
            'slug' => 'recurring-invoicing',
            'kicker' => 'Recurring Invoicing',
            'h1' => 'Recurring invoicing',
            'h1_highlight' => 'set it once, get paid every month',
            'title' => 'Recurring Invoicing | Automate Repeat Invoices | Inveqi',
            'meta_description' => 'Recurring invoicing to automatically bill subscriptions, retainers and ongoing services. Schedule, pause and clone with Inveqi. Start your free 14-day trial.',
            'meta_keywords' => 'recurring invoicing, recurring invoices, recurring billing, automatic invoices, subscription billing, repeat invoices, auto billing software',
            'subtitle' => 'Stop recreating the same invoice every month. Inveqi bills your recurring customers automatically so your cash flow stays predictable.',
            'cta_text' => 'Automate recurring billing',
            'screenshots_intro' => 'Schedule a series once and let Inveqi handle the rest.',
            'benefits_title' => 'Why automate recurring invoicing',
            'benefits_intro' => 'Recurring revenue deserves billing that runs itself.',
            'benefits' => [
                ['icon' => 'fa-hand-pointer', 'title' => 'Set and forget', 'desc' => 'Create a schedule once; Inveqi generates and sends each invoice automatically.'],
                ['icon' => 'fa-wave-square', 'title' => 'Steady cash flow', 'desc' => 'Predictable monthly income from repeat customers.'],
                ['icon' => 'fa-arrow-rotate-right', 'title' => 'Never miss a billing', 'desc' => 'Automatic generation means no manual laps to forget.'],
                ['icon' => 'fa-pause', 'title' => 'Full control', 'desc' => 'Pause, resume or clone any series in a single click.'],
                ['icon' => 'fa-clock-rotate-left', 'title' => 'Save hours', 'desc' => 'Reclaim the time you spent duplicating invoices.'],
                ['icon' => 'fa-credit-card', 'title' => 'Faster payment', 'desc' => 'Pair with Stripe so recurring invoices can be paid online instantly.'],
            ],
            'features_title' => 'Recurring invoicing that runs itself',
            'features_intro' => 'Scheduling, automation and control built in.',
            'features' => [
                ['icon' => 'fa-calendar-check', 'title' => 'Flexible schedules', 'desc' => 'Bill weekly, bi-weekly, monthly or yearly.'],
                ['icon' => 'fa-repeat', 'title' => 'Auto-generation', 'desc' => 'Invoices create themselves on schedule without input.'],
                ['icon' => 'fa-envelope', 'title' => 'Auto-send', 'desc' => 'Email each generated invoice to the customer automatically.'],
                ['icon' => 'fa-circle-pause', 'title' => 'Pause & resume', 'desc' => 'Stop or restart any series as customer needs change.'],
                ['icon' => 'fa-copy', 'title' => 'Clone series', 'desc' => 'Duplicate a recurring setup for a new customer in seconds.'],
                ['icon' => 'fa-bell', 'title' => 'Retry logic', 'desc' => 'Smart retries help overdue recurring invoices get paid.'],
                ['icon' => 'fa-chart-line', 'title' => 'MRR tracking', 'desc' => 'See your recurring revenue and active series at a glance.'],
                ['icon' => 'fa-pen', 'title' => 'Custom amounts', 'desc' => 'Set fixed or adjustable amounts per billing cycle.'],
                ['icon' => 'fa-cloud', 'title' => 'Secure cloud', 'desc' => 'All your schedules managed in one safe workspace.'],
            ],
            'use_cases_title' => 'Who should use recurring invoicing',
            'use_cases_intro' => 'Any business with repeat billing.',
            'use_cases' => [
                ['icon' => 'fa-phone', 'title' => 'Subscription services', 'desc' => 'Bill customers automatically each billing period.'],
                ['icon' => 'fa-handshake', 'title' => 'Retainer-based agencies', 'desc' => 'Invoice monthly retainers without manual recreating.'],
                ['icon' => 'fa-home', 'title' => 'Landlords', 'desc' => 'Send monthly rent or service invoices on autopilot.'],
                ['icon' => 'fa-laptop-code', 'title' => 'SaaS & hosting', 'desc' => 'Recurring billing for software and hosting plans.'],
            ],
            'internal_links' => [
                ['title' => 'Invoice Automation', 'url' => '/invoice-automation', 'desc' => 'Automate reminders and billing workflows.'],
                ['title' => 'Billing Software', 'url' => '/billing-software', 'desc' => 'The complete billing platform.'],
                ['title' => 'Stripe Invoicing', 'url' => '/stripe-invoicing', 'desc' => 'Collect card payments on every invoice.'],
                ['title' => 'Invoicing Software', 'url' => '/invoicing-software', 'desc' => 'Create, send and track invoices online.'],
            ],
            'faqs_title' => 'Recurring invoicing FAQ',
            'faqs' => [
                ['q' => 'How does recurring invoicing work?', 'a' => 'You set a schedule (e.g. monthly) and Inveqi automatically creates and sends the invoice on each billing date.'],
                ['q' => 'Can I pause a recurring series?', 'a' => 'Yes. Pause any series anytime and resume it later â€” or clone it for a new customer.'],
                ['q' => 'Can customers pay recurring invoices online?', 'a' => 'Yes. With Stripe enabled, each auto-generated invoice includes a secure online payment link.'],
                ['q' => 'Can I change the billed amount?', 'a' => 'Yes, you can set and adjust amounts per series or per individual cycle.'],
            ],
            'schema' => '{
                "@context": "https://schema.org",
                "@type": "SoftwareApplication",
                "name": "Inveqi Recurring Invoicing",
                "applicationCategory": "BusinessApplication",
                "operatingSystem": "Web",
                "url": "__CANONICAL__",
                "description": "Recurring invoicing to automatically bill subscriptions, retainers and ongoing services.",
                "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
                "aggregateRating": { "@type": "AggregateRating", "ratingValue": "4.8", "ratingCount": "128" }
            }',
        ],

        'invoice-automation' => [
            'slug' => 'invoice-automation',
            'kicker' => 'Invoice Automation',
            'h1' => 'Invoice automation',
            'h1_highlight' => 'spend less time on billing',
            'title' => 'Invoice Automation | Automate Billing & Reminders | Inveqi',
            'meta_description' => 'Invoice automation to create, send and follow up on invoices automatically. Recurring billing, reminders and webhooks with Inveqi. Start free for 14 days.',
            'meta_keywords' => 'invoice automation, automate invoicing, automatic invoice generation, automated billing, invoice reminders automation, accounting automation',
            'subtitle' => 'Automate the repetitive parts of billing â€” creation, sending and follow-up â€” so your team spends time on customers, not spreadsheets.',
            'cta_text' => 'Automate your invoicing',
            'screenshots_intro' => 'Put invoicing on autopilot and reclaim your time.',
            'benefits_title' => 'The impact of invoice automation',
            'benefits_intro' => 'Automation turns billing from a chore into a background process.',
            'benefits' => [
                ['icon' => 'fa-hourglass-half', 'title' => 'Hours saved weekly', 'desc' => 'Automate the repetitive steps you used to do by hand.'],
                ['icon' => 'fa-arrow-trend-up', 'title' => 'Fewer payment delays', 'desc' => 'Automatic reminders mean invoices get paid sooner.'],
                ['icon' => 'fa-robot', 'title' => 'Consistent process', 'desc' => 'Every invoice follows the same proven flow, every time.'],
                ['icon' => 'fa-headset', 'title' => 'Free up your team', 'desc' => 'Let staff focus on high-value work instead of billing chores.'],
                ['icon' => 'fa-gears', 'title' => 'Connect your stack', 'desc' => 'Webhooks push invoice and payment events to your tools.'],
                ['icon' => 'fa-chart-line', 'title' => 'Better visibility', 'desc' => 'Automation surfaces status automatically so nothing stalls.'],
            ],
            'features_title' => 'Automation features that just work',
            'features_intro' => 'Set rules once; benefit forever.',
            'features' => [
                ['icon' => 'fa-calendar-plus', 'title' => 'Scheduled generation', 'desc' => 'Create invoices automatically on a repeating schedule.'],
                ['icon' => 'fa-paper-plane', 'title' => 'Automatic sending', 'desc' => 'Email invoices to customers the moment they are generated.'],
                ['icon' => 'fa-bell', 'title' => 'Reminder workflows', 'desc' => 'Automated follow-up emails at intervals you define.'],
                ['icon' => 'fa-diagram-project', 'title' => 'Status automation', 'desc' => 'Invoice status updates automatically as events happen.'],
                ['icon' => 'fa-plug', 'title' => 'Webhooks', 'desc' => 'Forward events to apps like your CRM or accounting tool.'],
                ['icon' => 'fa-clipboard-check', 'title' => 'Rule-based logic', 'desc' => 'Define when and how invoices and reminders trigger.'],
                ['icon' => 'fa-chart-pie', 'title' => 'Automated reports', 'desc' => 'Billing dashboards update themselves in real time.'],
                ['icon' => 'fa-shield-halved', 'title' => 'Audit trail', 'desc' => 'Every automated action is logged for full visibility.'],
                ['icon' => 'fa-users', 'title' => 'Team automation', 'desc' => 'Share automation rules across your whole team.'],
            ],
            'use_cases_title' => 'Who benefits from invoice automation',
            'use_cases_intro' => 'From solo founders to finance teams.',
            'use_cases' => [
                ['icon' => 'fa-user-astronaut', 'title' => 'Solo founders', 'desc' => 'Automate the billing you used to do on weekends.'],
                ['icon' => 'fa-building-columns', 'title' => 'Finance teams', 'desc' => 'Standardize billing and reporting across the org.'],
                ['icon' => 'fa-display-chart-up', 'title' => 'Operations leads', 'desc' => 'Keep billing flowing without manual checks.'],
                ['icon' => 'fa-shop', 'title' => 'E-commerce merchants', 'desc' => 'Automate invoices and receipts for online orders.'],
            ],
            'internal_links' => [
                ['title' => 'Recurring Invoicing', 'url' => '/recurring-invoicing', 'desc' => 'Automate repeat invoices end to end.'],
                ['title' => 'Invoice Automation', 'url' => '/invoice-automation', 'desc' => 'Explore all automation workflows.'],
                ['title' => 'Billing Software', 'url' => '/billing-software', 'desc' => 'The complete automated billing platform.'],
                ['title' => 'Invoicing Software', 'url' => '/invoicing-software', 'desc' => 'Create, send and track invoices online.'],
            ],
            'faqs_title' => 'Invoice automation FAQ',
            'faqs' => [
                ['q' => 'What can I automate with invoicing?', 'a' => 'Creation, sending, payment reminders and status updates â€” so repeat billing runs without manual effort.'],
                ['q' => 'Can I connect automated invoices to other tools?', 'a' => 'Yes. Webhooks let you push invoice and payment events to your CRM, accounting and other apps.'],
                ['q' => 'How often can invoices be automated?', 'a' => 'On any schedule you define â€” daily, weekly, monthly, yearly or custom intervals.'],
                ['q' => 'Will automation get my reminders right?', 'a' => 'Yes. Reminder rules you set ensure polite, timely follow-ups on every overdue invoice.'],
            ],
            'schema' => '{
                "@context": "https://schema.org",
                "@type": "SoftwareApplication",
                "name": "Inveqi Invoice Automation",
                "applicationCategory": "BusinessApplication",
                "operatingSystem": "Web",
                "url": "__CANONICAL__",
                "description": "Invoice automation to create, send and follow up on invoices automatically.",
                "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
                "aggregateRating": { "@type": "AggregateRating", "ratingValue": "4.8", "ratingCount": "128" }
            }',
        ],

        'estimate-invoice-software' => [
            'slug' => 'estimate-invoice-software',
            'kicker' => 'Estimate & Invoice Software',
            'h1' => 'Estimate and invoice software',
            'h1_highlight' => 'from quote to paid, seamlessly',
            'title' => 'Estimate & Invoice Software | Quotes to Invoices | Inveqi',
            'meta_description' => 'Estimate and invoice software to send polished quotes, get online approval, and auto-convert to invoices. Streamline your quoting with Inveqi. Start free.',
            'meta_keywords' => 'estimate software, quote software, estimate invoice software, quotation software, proposal software, convert quote to invoice, online estimates',
            'subtitle' => 'Send professional estimates, let clients approve online, and convert approved quotes into invoices automatically â€” no copy-paste, no double entry.',
            'cta_text' => 'Create your first estimate',
            'screenshots_intro' => 'From quote request to paid invoice in one smooth flow.',
            'benefits_title' => 'Why estimate and invoice software pays off',
            'benefits_intro' => 'Win more jobs and get paid faster with quotes that convert.',
            'benefits' => [
                ['icon' => 'fa-file-signature', 'title' => 'Convert more quotes', 'desc' => 'A polished, branded estimate builds trust and wins business.'],
                ['icon' => 'fa-thumbs-up', 'title' => 'Online approval', 'desc' => 'Clients approve quotes with one click, right from their email.'],
                ['icon' => 'fa-right-left', 'title' => 'Simple quote-to-invoice', 'desc' => 'Approved estimates convert to invoices automatically.'],
                ['icon' => 'fa-stopwatch', 'title' => 'Faster turnaround', 'desc' => 'Skip the email ping-pong and close jobs sooner.'],
                ['icon' => 'fa-clock', 'title' => 'Expiry control', 'desc' => 'Set expiry dates so favorable pricing is not held forever.'],
                ['icon' => 'fa-th-list', 'title' => 'Version history', 'desc' => 'Keep every revision of a quote in one place.'],
            ],
            'features_title' => 'Built for the quote-to-invoice journey',
            'features_intro' => 'Every tool to manage estimates and invoices together.',
            'features' => [
                ['icon' => 'fa-file-invoice', 'title' => 'Estimate builder', 'desc' => 'Create itemized estimates with the same easy editor.'],
                ['icon' => 'fa-check-circle', 'title' => 'One-click approval', 'desc' => 'Clients accept estimates online in a single click.'],
                ['icon' => 'fa-rotate', 'title' => 'Auto-conversion', 'desc' => 'Approved estimates become invoices automatically.'],
                ['icon' => 'fa-calendar', 'title' => 'Expiry dates', 'desc' => 'Control how long a quoted price stays valid.'],
                ['icon' => 'fa-clone', 'title' => 'Duplicate & edit', 'desc' => 'Clone estimates and adjust for a similar job.'],
                ['icon' => 'fa-palette', 'title' => 'Branded templates', 'desc' => 'Match your logo, colors and style on every quote.'],
                ['icon' => 'fa-envelope', 'title' => 'Email delivery', 'desc' => 'Send estimates and invoices directly from the workspace.'],
                ['icon' => 'fa-chart-line', 'title' => 'Conversion tracking', 'desc' => 'See which quotes turn into invoices and revenue.'],
                ['icon' => 'fa-file-pdf', 'title' => 'PDF export', 'desc' => 'Download print-ready estimates and invoices anytime.'],
            ],
            'use_cases_title' => 'Who benefits from estimate software',
            'use_cases_intro' => 'Every business that quotes before it bills.',
            'use_cases' => [
                ['icon' => 'fa-hammer', 'title' => 'Contractors & trades', 'desc' => 'Quote jobs, win approval and bill on completion.'],
                ['icon' => 'fa-brush', 'title' => 'Designers & agencies', 'desc' => 'Present project estimates and convert to invoices.'],
                ['icon' => 'fa-camera', 'title' => 'Photographers & planners', 'desc' => 'Send packages as estimates, collect on approval.'],
                ['icon' => 'fa-home', 'title' => 'Home services', 'desc' => 'Estimate repairs and services, then invoice efficiently.'],
            ],
            'internal_links' => [
                ['title' => 'Invoice Generator', 'url' => '/invoice-generator', 'desc' => 'Create a professional invoice in seconds.'],
                ['title' => 'Invoicing Software', 'url' => '/invoicing-software', 'desc' => 'Create, send and track invoices online.'],
                ['title' => 'Small Business Invoicing', 'url' => '/small-business-invoicing', 'desc' => 'Streamline small business billing.'],
                ['title' => 'Invoice Management Software', 'url' => '/invoice-management-software', 'desc' => 'Organize and track every invoice.'],
            ],
            'faqs_title' => 'Estimate and invoice software FAQ',
            'faqs' => [
                ['q' => 'How does an estimate become an invoice?', 'a' => 'When a client approves your estimate online, Inveqi automatically converts it into an invoice for you.'],
                ['q' => 'Can clients approve estimates online?', 'a' => 'Yes. Each estimate includes a secure link where clients can review and approve it with one click.'],
                ['q' => 'Can I set estimate expiry dates?', 'a' => 'Yes, set an expiry so the quoted price is only valid until a date you choose.'],
                ['q' => 'Can I use the same templates for estimates and invoices?', 'a' => 'Yes, apply the same branding and templates across both estimates and invoices.'],
            ],
            'schema' => '{
                "@context": "https://schema.org",
                "@type": "SoftwareApplication",
                "name": "Inveqi Estimate and Invoice Software",
                "applicationCategory": "BusinessApplication",
                "operatingSystem": "Web",
                "url": "__CANONICAL__",
                "description": "Estimate and invoice software to send quotes, get approval and convert to invoices.",
                "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
                "aggregateRating": { "@type": "AggregateRating", "ratingValue": "4.8", "ratingCount": "128" }
            }',
        ],

        'stripe-invoicing' => [
            'slug' => 'stripe-invoicing',
            'kicker' => 'Stripe Invoicing',
            'h1' => 'Stripe invoicing',
            'h1_highlight' => 'get paid directly on every invoice',
            'title' => 'Stripe Invoicing | Accept Card Payments on Invoices | Inveqi',
            'meta_description' => 'Add Stripe invoicing to your workflow. Send invoices with secure online card payments, automatic reconciliation and recurring billing. Start your free trial.',
            'meta_keywords' => 'stripe invoicing, stripe invoice, accept payments invoice, online card payments, stripe payment integration, pay invoice online, invoice payment link',
            'subtitle' => 'Put a secure Stripe payment link on every invoice so customers can pay by card instantly â€” no bank transfers, no chasing checks.',
            'cta_text' => 'Start accepting payments',
            'screenshots_intro' => 'Turn every invoice into a secure payment page.',
            'benefits_title' => 'Why Stripe invoicing matters',
            'benefits_intro' => 'Online payments dramatically shorten the time from invoice to money in the bank.',
            'benefits' => [
                ['icon' => 'fa-bolt', 'title' => 'Get paid instantly', 'desc' => 'Customers pay by card in seconds from their invoice email.'],
                ['icon' => 'fa-shield-halved', 'title' => 'Secure checkout', 'desc' => 'Stripe bank-grade security protects every transaction.'],
                ['icon' => 'fa-repeat', 'title' => 'Perfect for recurring', 'desc' => 'Card payments pair naturally with recurring invoices.'],
                ['icon' => 'fa-arrow-trend-down', 'title' => 'Fewer late payments', 'desc' => 'A convenient payment link removes friction to paying.'],
                ['icon' => 'fa-arrows-rotate', 'title' => 'Auto reconciliation', 'desc' => 'Paid invoices update automatically â€” no manual matching.'],
                ['icon' => 'fa-globe', 'title' => 'Global payments', 'desc' => 'Accept cards from customers around the world.'],
            ],
            'features_title' => 'Stripe invoicing features',
            'features_intro' => 'Payments that integrate cleanly with billing.',
            'features' => [
                ['icon' => 'fa-link', 'title' => 'Payment links', 'desc' => 'Every invoice carries a secure online payment link.'],
                ['icon' => 'fa-credit-card', 'title' => 'Card payments', 'desc' => 'Accept Visa, Mastercard, Amex and more by card.'],
                ['icon' => 'fa-bolt', 'title' => 'Instant confirmation', 'desc' => 'Invoice status updates the moment a payment lands.'],
                ['icon' => 'fa-arrows-rotate', 'title' => 'Auto reconciliation', 'desc' => 'Payments sync automatically to your invoice records.'],
                ['icon' => 'fa-repeat', 'title' => 'Subscriptions', 'desc' => 'Pair with recurring invoicing for steady card billing.'],
                ['icon' => 'fa-shield-halved', 'title' => 'Secure checkout', 'desc' => 'PCI-compliant payments through Stripe.'],
                ['icon' => 'fa-globe', 'title' => 'Multi-currency', 'desc' => 'Bill and collect in many currencies.'],
                ['icon' => 'fa-chart-line', 'title' => 'Payment reports', 'desc' => 'See what is paid and outstanding at a glance.'],
                ['icon' => 'fa-bell', 'title' => 'Failure alerts', 'desc' => 'Get notified if a card payment encounters an issue.'],
            ],
            'use_cases_title' => 'Who uses Stripe invoicing',
            'use_cases_intro' => 'Any business that wants to be paid faster online.',
            'use_cases' => [
                ['icon' => 'fa-laptop', 'title' => 'Online businesses', 'desc' => 'Collect card payments for digital services instantly.'],
                ['icon' => 'fa-satellite-dish', 'title' => 'Subscriptions', 'desc' => 'Recurring card billing for memberships and plans.'],
                ['icon' => 'fa-briefcase', 'title' => 'Consultancies', 'desc' => 'Ask clients to pay project invoices by card online.'],
                ['icon' => 'fa-globe', 'title' => 'International sellers', 'desc' => 'Accept payments from customers worldwide in multiple currencies.'],
            ],
            'internal_links' => [
                ['title' => 'Billing Software', 'url' => '/billing-software', 'desc' => 'Automate billing and payments together.'],
                ['title' => 'Recurring Invoicing', 'url' => '/recurring-invoicing', 'desc' => 'Pair card payments with recurring billing.'],
                ['title' => 'Online Invoice Software', 'url' => '/online-invoice-software', 'desc' => 'The full web-based invoicing workflow.'],
                ['title' => 'Invoicing Software', 'url' => '/invoicing-software', 'desc' => 'Create, send and track invoices online.'],
            ],
            'faqs_title' => 'Stripe invoicing FAQ',
            'faqs' => [
                ['q' => 'How do I enable Stripe on my invoices?', 'a' => 'Connect your Stripe account in settings, then every invoice automatically includes a secure online payment link.'],
                ['q' => 'Is paying on an invoice secure?', 'a' => 'Yes. Payments are processed by Stripe with PCI-compliant, bank-grade encryption.'],
                ['q' => 'Can customers pay recurring invoices by card?', 'a' => 'Yes. Recurring invoices include the same secure payment link for easy card payments.'],
                ['q' => 'Does the invoice update automatically when paid?', 'a' => 'Yes. When a payment is received, the invoice status updates automatically without manual work.'],
            ],
            'schema' => '{
                "@context": "https://schema.org",
                "@type": "SoftwareApplication",
                "name": "Inveqi Stripe Invoicing",
                "applicationCategory": "BusinessApplication",
                "operatingSystem": "Web",
                "url": "__CANONICAL__",
                "description": "Stripe invoicing to accept secure online card payments on every invoice.",
                "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
                "aggregateRating": { "@type": "AggregateRating", "ratingValue": "4.8", "ratingCount": "128" }
            }',
        ],

        'small-business-invoicing' => [
            'slug' => 'small-business-invoicing',
            'kicker' => 'Small Business Invoicing',
            'h1' => 'Small business invoicing',
            'h1_highlight' => 'built for how you actually work',
            'title' => 'Small Business Invoicing | Simple Affordable Billing | Inveqi',
            'meta_description' => 'Small business invoicing that is simple, affordable and professional. Create invoices, track payments and get paid with Stripe. Start your free 14-day trial.',
            'meta_keywords' => 'small business invoicing, invoicing for small business, invoice software small business, small business billing, business invoice software, invoice app for small business',
            'subtitle' => 'Invoicing that does not need a finance team. Simple to learn, affordable to run, and professional enough to impress your customers.',
            'cta_text' => 'Start invoicing your business',
            'screenshots_intro' => 'Built to be easy for small teams from day one.',
            'benefits_title' => 'Invoicing made for small business',
            'benefits_intro' => 'You built a business, not a billing department. Inveqi keeps things simple.',
            'benefits' => [
                ['icon' => 'fa-child-reaching', 'title' => 'Easy to learn', 'desc' => 'Intuitive design means your team is up and running on day one.'],
                ['icon' => 'fa-wallet', 'title' => 'Affordable plans', 'desc' => 'Start free and only pay when your business grows.'],
                ['icon' => 'fa-bolt', 'title' => 'Fast to use', 'desc' => 'Create and send polished invoices in under a minute.'],
                ['icon' => 'fa-credit-card', 'title' => 'Get paid faster', 'desc' => 'Accept card payments online so cash flow stays healthy.'],
                ['icon' => 'fa-chart-simple', 'title' => 'Simple reports', 'desc' => 'Understand revenue and overdue balances without a finance degree.'],
                ['icon' => 'fa-mobile-screen', 'title' => 'Works anywhere', 'desc' => 'Invoice from your laptop, tablet or phone.'],
            ],
            'features_title' => 'Small business features that just work',
            'features_intro' => 'Everything you need, nothing that you do not.',
            'features' => [
                ['icon' => 'fa-file-invoice', 'title' => 'Simple invoices', 'desc' => 'Create clear, professional invoices in seconds.'],
                ['icon' => 'fa-paper-plane', 'title' => 'Send by email', 'desc' => 'Email invoices directly and track delivery.'],
                ['icon' => 'fa-credit-card', 'title' => 'Card payments', 'desc' => 'Collect Stripe payments right on the invoice.'],
                ['icon' => 'fa-bell', 'title' => 'Payment reminders', 'desc' => 'Automated nudges for overdue invoices.'],
                ['icon' => 'fa-repeat', 'title' => 'Recurring billing', 'desc' => 'Automate repeat invoicing for regular customers.'],
                ['icon' => 'fa-user-plus', 'title' => 'Customer records', 'desc' => 'Store customers and products to speed up billing.'],
                ['icon' => 'fa-file-pdf', 'title' => 'PDF export', 'desc' => 'Download and share print-ready PDFs.'],
                ['icon' => 'fa-chart-line', 'title' => 'Reports', 'desc' => 'Track revenue and outstanding balances easily.'],
                ['icon' => 'fa-headset', 'title' => 'Friendly support', 'desc' => 'Helpful support when you need it.'],
            ],
            'use_cases_title' => 'Who uses small business invoicing',
            'use_cases_intro' => 'Simple tools for every kind of small business.',
            'use_cases' => [
                ['icon' => 'fa-store', 'title' => 'Local shops', 'desc' => 'Create professional invoices for B2B customers.'],
                ['icon' => 'fa-scissors', 'title' => 'Salons & studios', 'desc' => 'Invoice services and packages simply.'],
                ['icon' => 'fa-plug', 'title' => 'Trades & contractors', 'desc' => 'Quote and invoice jobs without paperwork.'],
                ['icon' => 'fa-laptop', 'title' => 'Home-based businesses', 'desc' => 'Look professional and get paid on time.'],
            ],
            'internal_links' => [
                ['title' => 'Invoice Generator', 'url' => '/invoice-generator', 'desc' => 'Create a professional invoice for free.'],
                ['title' => 'Invoicing Software', 'url' => '/invoicing-software', 'desc' => 'The complete invoicing platform.'],
                ['title' => 'Billing Software', 'url' => '/billing-software', 'desc' => 'Full billing automation for growing teams.'],
                ['title' => 'Online Invoice Software', 'url' => '/online-invoice-software', 'desc' => 'Work entirely in your browser.'],
            ],
            'faqs_title' => 'Small business invoicing FAQ',
            'faqs' => [
                ['q' => 'Is invoicing software worth it for a small business?', 'a' => 'Yes. It saves hours, reduces errors, and helps you get paid faster â€” often paying for itself quickly.'],
                ['q' => 'Can I start for free?', 'a' => 'Yes. Start with a free plan or a 14-day trial with no credit card required.'],
                ['q' => 'Do I need accounting knowledge to use it?', 'a' => 'No. Inveqi is designed to be simple, with clear invoices and easy-to-read reports.'],
                ['q' => 'Can customers pay invoices online?', 'a' => 'Yes. With Stripe enabled, customers can pay by card through a secure link on each invoice.'],
            ],
            'schema' => '{
                "@context": "https://schema.org",
                "@type": "SoftwareApplication",
                "name": "Inveqi Small Business Invoicing",
                "applicationCategory": "BusinessApplication",
                "operatingSystem": "Web",
                "url": "__CANONICAL__",
                "description": "Simple, affordable invoicing software built for small businesses.",
                "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
                "aggregateRating": { "@type": "AggregateRating", "ratingValue": "4.8", "ratingCount": "128" }
            }',
        ],

    ],

];
